package com.book.web.pojo.raw;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..student.id
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    private String id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..student.name
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..student.age
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..student.sex
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..student.data
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    private Date data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..student.id
     *
     * @return the value of test..student.id
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..student.id
     *
     * @param id the value for test..student.id
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..student.name
     *
     * @return the value of test..student.name
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..student.name
     *
     * @param name the value for test..student.name
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..student.age
     *
     * @return the value of test..student.age
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..student.age
     *
     * @param age the value for test..student.age
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..student.sex
     *
     * @return the value of test..student.sex
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..student.sex
     *
     * @param sex the value for test..student.sex
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..student.data
     *
     * @return the value of test..student.data
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    public Date getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..student.data
     *
     * @param data the value for test..student.data
     *
     * @mbggenerated Fri Jun 30 10:57:08 CST 2017
     */
    public void setData(Date data) {
        this.data = data;
    }
}